# coding: utf-8

# flake8: noqa

"""
DEP Authorization Service

Draft contract for the WP4 Authorization Service. See docs/design/design-005-authorization-service-api.md.  One typed endpoint per operation, so a generated client exposes one function per decision. Operations without an endpoint of their own go through /v1/decisions/privileged-operations.  A decision is returned with HTTP 200 whether it permits or denies. Any non-200 response is an error, and PEPs MUST treat it as a deny.  Subject claims (entitlements, acr) come from the caller's own OAuth2 bearer token, validated by this service, not from the request body. The body carries only what the token cannot supply: which subject the decision concerns (for logging, and for credentials that carry no token at all, such as the root bootstrap) and resource ownership facts the PEP resolves from its own database.   # noqa: E501

The version of the OpenAPI document: 0.1.0-draft
Generated by: https://openapi-generator.tech
"""

from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from rucio_authz_client.api.dids_api import DidsApi
from rucio_authz_client.api.operations_api import OperationsApi
from rucio_authz_client.api.privileged_api import PrivilegedApi
from rucio_authz_client.api.protocols_api import ProtocolsApi
from rucio_authz_client.api.replicas_api import ReplicasApi
from rucio_authz_client.api.rses_api import RsesApi
from rucio_authz_client.api.rules_api import RulesApi

# import ApiClient
from rucio_authz_client.api_client import ApiClient
from rucio_authz_client.configuration import Configuration
from rucio_authz_client.exceptions import OpenApiException
from rucio_authz_client.exceptions import ApiTypeError
from rucio_authz_client.exceptions import ApiValueError
from rucio_authz_client.exceptions import ApiKeyError
from rucio_authz_client.exceptions import ApiAttributeError
from rucio_authz_client.exceptions import ApiException

# import models into sdk package
from rucio_authz_client.models.context import Context
from rucio_authz_client.models.decision import Decision
from rucio_authz_client.models.decision_context import DecisionContext
from rucio_authz_client.models.decision_context_policy import DecisionContextPolicy
from rucio_authz_client.models.did import Did
from rucio_authz_client.models.did_attach_request import DidAttachRequest
from rucio_authz_client.models.did_create_request import DidCreateRequest
from rucio_authz_client.models.did_detach_request import DidDetachRequest
from rucio_authz_client.models.health_status import HealthStatus
from rucio_authz_client.models.privileged_operation_request import PrivilegedOperationRequest
from rucio_authz_client.models.problem import Problem
from rucio_authz_client.models.protocol import Protocol
from rucio_authz_client.models.protocol_create_request import ProtocolCreateRequest
from rucio_authz_client.models.protocol_delete_request import ProtocolDeleteRequest
from rucio_authz_client.models.protocol_update_request import ProtocolUpdateRequest
from rucio_authz_client.models.replica_delete_request import ReplicaDeleteRequest
from rucio_authz_client.models.replica_register_request import ReplicaRegisterRequest
from rucio_authz_client.models.rse import Rse
from rucio_authz_client.models.rse_attribute_delete_request import RseAttributeDeleteRequest
from rucio_authz_client.models.rse_attribute_delete_request_attribute import (
    RseAttributeDeleteRequestAttribute,
)
from rucio_authz_client.models.rse_attribute_set_request import RseAttributeSetRequest
from rucio_authz_client.models.rse_attribute_set_request_attribute import (
    RseAttributeSetRequestAttribute,
)
from rucio_authz_client.models.rse_create_request import RseCreateRequest
from rucio_authz_client.models.rse_delete_request import RseDeleteRequest
from rucio_authz_client.models.rse_update_request import RseUpdateRequest
from rucio_authz_client.models.rse_update_request_changes import RseUpdateRequestChanges
from rucio_authz_client.models.rule import Rule
from rucio_authz_client.models.rule_create_request import RuleCreateRequest
from rucio_authz_client.models.rule_create_request_rule import RuleCreateRequestRule
from rucio_authz_client.models.rule_delete_request import RuleDeleteRequest
from rucio_authz_client.models.rule_update_request import RuleUpdateRequest
from rucio_authz_client.models.rule_update_request_changes import RuleUpdateRequestChanges
from rucio_authz_client.models.scope import Scope
from rucio_authz_client.models.subject import Subject
