# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-20T10:26:28+00:00

from __future__ import annotations

from fastapi import APIRouter

router = APIRouter(tags=["operations"])


@router.get("/healthz", response_model=None, tags=["operations"])
async def get_health() -> None:
    """
    Liveness and PDP reachability
    """
    pass
