"""
DEP Authorization Service

Draft contract for the WP4 Authorization Service. See docs/design/design-005-authorization-service-api.md.  One typed endpoint per operation, so a generated client exposes one function per decision. Operations without an endpoint of their own go through /v1/decisions/privileged-operations.  A decision is returned with HTTP 200 whether it permits or denies. Any non-200 response is an error, and PEPs MUST treat it as a deny.  Subject claims (entitlements, acr) come from the caller's own OAuth2 bearer token, validated by this service, not from the request body. The body carries only what the token cannot supply: which subject the decision concerns (for logging, and for credentials that carry no token at all, such as the root bootstrap) and resource ownership facts the PEP resolves from its own database.   # noqa: E501

The version of the OpenAPI document: 0.1.0-draft
Generated by: https://openapi-generator.tech
"""

try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401

import six

from rucio_authz_client.configuration import Configuration


class DecisionContext:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "decision_id": "object",
        "reason_admin": "object",
        "policy": "DecisionContextPolicy",
    }

    attribute_map = {
        "decision_id": "decision_id",
        "reason_admin": "reason_admin",
        "policy": "policy",
    }

    def __init__(
        self, decision_id=None, reason_admin=None, policy=None, local_vars_configuration=None
    ):  # noqa: E501
        """DecisionContext - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._decision_id = None
        self._reason_admin = None
        self._policy = None
        self.discriminator = None

        self.decision_id = decision_id
        self.reason_admin = reason_admin
        if policy is not None:
            self.policy = policy

    @property
    def decision_id(self):
        """Gets the decision_id of this DecisionContext.  # noqa: E501

        Identifier of the audit record for this decision. PEPs log it next to their own request id to correlate the two.   # noqa: E501

        :return: The decision_id of this DecisionContext.  # noqa: E501
        :rtype: object
        """
        return self._decision_id

    @decision_id.setter
    def decision_id(self, decision_id):
        """Sets the decision_id of this DecisionContext.

        Identifier of the audit record for this decision. PEPs log it next to their own request id to correlate the two.   # noqa: E501

        :param decision_id: The decision_id of this DecisionContext.  # noqa: E501
        :type decision_id: object
        """

        self._decision_id = decision_id

    @property
    def reason_admin(self):
        """Gets the reason_admin of this DecisionContext.  # noqa: E501

        Operator-facing reason. Not for end users.  # noqa: E501

        :return: The reason_admin of this DecisionContext.  # noqa: E501
        :rtype: object
        """
        return self._reason_admin

    @reason_admin.setter
    def reason_admin(self, reason_admin):
        """Sets the reason_admin of this DecisionContext.

        Operator-facing reason. Not for end users.  # noqa: E501

        :param reason_admin: The reason_admin of this DecisionContext.  # noqa: E501
        :type reason_admin: object
        """

        self._reason_admin = reason_admin

    @property
    def policy(self):
        """Gets the policy of this DecisionContext.  # noqa: E501


        :return: The policy of this DecisionContext.  # noqa: E501
        :rtype: DecisionContextPolicy
        """
        return self._policy

    @policy.setter
    def policy(self, policy):
        """Sets the policy of this DecisionContext.


        :param policy: The policy of this DecisionContext.  # noqa: E501
        :type policy: DecisionContextPolicy
        """

        self._policy = policy

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(lambda x: convert(x), value))
            elif isinstance(value, dict):
                result[attr] = dict(map(lambda item: (item[0], convert(item[1])), value.items()))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DecisionContext):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DecisionContext):
            return True

        return self.to_dict() != other.to_dict()
