"""
DEP Authorization Service

Draft contract for the WP4 Authorization Service. See docs/design/design-005-authorization-service-api.md.  One typed endpoint per operation, so a generated client exposes one function per decision. Operations without an endpoint of their own go through /v1/decisions/privileged-operations.  A decision is returned with HTTP 200 whether it permits or denies. Any non-200 response is an error, and PEPs MUST treat it as a deny.  Subject claims (entitlements, acr) come from the caller's own OAuth2 bearer token, validated by this service, not from the request body. The body carries only what the token cannot supply: which subject the decision concerns (for logging, and for credentials that carry no token at all, such as the root bootstrap) and resource ownership facts the PEP resolves from its own database.   # noqa: E501

The version of the OpenAPI document: 0.1.0-draft
Generated by: https://openapi-generator.tech
"""

try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401

import six

from rucio_authz_client.configuration import Configuration


class RseAttributeSetRequestAttribute:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"key": "object", "value": "object"}

    attribute_map = {"key": "key", "value": "value"}

    def __init__(self, key=None, value=None, local_vars_configuration=None):  # noqa: E501
        """RseAttributeSetRequestAttribute - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._key = None
        self._value = None
        self.discriminator = None

        self.key = key
        self.value = value

    @property
    def key(self):
        """Gets the key of this RseAttributeSetRequestAttribute.  # noqa: E501


        :return: The key of this RseAttributeSetRequestAttribute.  # noqa: E501
        :rtype: object
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this RseAttributeSetRequestAttribute.


        :param key: The key of this RseAttributeSetRequestAttribute.  # noqa: E501
        :type key: object
        """

        self._key = key

    @property
    def value(self):
        """Gets the value of this RseAttributeSetRequestAttribute.  # noqa: E501

        The value being set. Not read by the phase 6 policy.  # noqa: E501

        :return: The value of this RseAttributeSetRequestAttribute.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this RseAttributeSetRequestAttribute.

        The value being set. Not read by the phase 6 policy.  # noqa: E501

        :param value: The value of this RseAttributeSetRequestAttribute.  # noqa: E501
        :type value: object
        """

        self._value = value

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(lambda x: convert(x), value))
            elif isinstance(value, dict):
                result[attr] = dict(map(lambda item: (item[0], convert(item[1])), value.items()))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RseAttributeSetRequestAttribute):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RseAttributeSetRequestAttribute):
            return True

        return self.to_dict() != other.to_dict()
