"""
DEP Authorization Service

Draft contract for the WP4 Authorization Service. See docs/design/design-005-authorization-service-api.md.  One typed endpoint per operation, so a generated client exposes one function per decision. Operations without an endpoint of their own go through /v1/decisions/privileged-operations.  A decision is returned with HTTP 200 whether it permits or denies. Any non-200 response is an error, and PEPs MUST treat it as a deny.  Subject claims (entitlements, acr) come from the caller's own OAuth2 bearer token, validated by this service, not from the request body. The body carries only what the token cannot supply: which subject the decision concerns (for logging, and for credentials that carry no token at all, such as the root bootstrap) and resource ownership facts the PEP resolves from its own database.   # noqa: E501

The version of the OpenAPI document: 0.1.0-draft
Generated by: https://openapi-generator.tech
"""

try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401

import six

from rucio_authz_client.configuration import Configuration


class RuleCreateRequestRule:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "owner": "object",
        "locked": "object",
        "rse_expression": "object",
        "source_rse_expression": "object",
        "dids": "object",
    }

    attribute_map = {
        "owner": "owner",
        "locked": "locked",
        "rse_expression": "rse_expression",
        "source_rse_expression": "source_rse_expression",
        "dids": "dids",
    }

    def __init__(
        self,
        owner=None,
        locked=None,
        rse_expression=None,
        source_rse_expression=None,
        dids=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """RuleCreateRequestRule - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._owner = None
        self._locked = None
        self._rse_expression = None
        self._source_rse_expression = None
        self._dids = None
        self.discriminator = None

        self.owner = owner
        self.locked = locked
        self.rse_expression = rse_expression
        self.source_rse_expression = source_rse_expression
        self.dids = dids

    @property
    def owner(self):
        """Gets the owner of this RuleCreateRequestRule.  # noqa: E501

        Account the new rule will belong to.  # noqa: E501

        :return: The owner of this RuleCreateRequestRule.  # noqa: E501
        :rtype: object
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this RuleCreateRequestRule.

        Account the new rule will belong to.  # noqa: E501

        :param owner: The owner of this RuleCreateRequestRule.  # noqa: E501
        :type owner: object
        """

        self._owner = owner

    @property
    def locked(self):
        """Gets the locked of this RuleCreateRequestRule.  # noqa: E501


        :return: The locked of this RuleCreateRequestRule.  # noqa: E501
        :rtype: object
        """
        return self._locked

    @locked.setter
    def locked(self, locked):
        """Sets the locked of this RuleCreateRequestRule.


        :param locked: The locked of this RuleCreateRequestRule.  # noqa: E501
        :type locked: object
        """

        self._locked = locked

    @property
    def rse_expression(self):
        """Gets the rse_expression of this RuleCreateRequestRule.  # noqa: E501


        :return: The rse_expression of this RuleCreateRequestRule.  # noqa: E501
        :rtype: object
        """
        return self._rse_expression

    @rse_expression.setter
    def rse_expression(self, rse_expression):
        """Sets the rse_expression of this RuleCreateRequestRule.


        :param rse_expression: The rse_expression of this RuleCreateRequestRule.  # noqa: E501
        :type rse_expression: object
        """

        self._rse_expression = rse_expression

    @property
    def source_rse_expression(self):
        """Gets the source_rse_expression of this RuleCreateRequestRule.  # noqa: E501


        :return: The source_rse_expression of this RuleCreateRequestRule.  # noqa: E501
        :rtype: object
        """
        return self._source_rse_expression

    @source_rse_expression.setter
    def source_rse_expression(self, source_rse_expression):
        """Sets the source_rse_expression of this RuleCreateRequestRule.


        :param source_rse_expression: The source_rse_expression of this RuleCreateRequestRule.  # noqa: E501
        :type source_rse_expression: object
        """

        self._source_rse_expression = source_rse_expression

    @property
    def dids(self):
        """Gets the dids of this RuleCreateRequestRule.  # noqa: E501


        :return: The dids of this RuleCreateRequestRule.  # noqa: E501
        :rtype: object
        """
        return self._dids

    @dids.setter
    def dids(self, dids):
        """Sets the dids of this RuleCreateRequestRule.


        :param dids: The dids of this RuleCreateRequestRule.  # noqa: E501
        :type dids: object
        """
        if (
            self.local_vars_configuration.client_side_validation
            and dids is not None
            and len(dids) < 1
        ):
            raise ValueError(
                "Invalid value for `dids`, number of items must be greater than or equal to `1`"
            )  # noqa: E501

        self._dids = dids

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(lambda x: convert(x), value))
            elif isinstance(value, dict):
                result[attr] = dict(map(lambda item: (item[0], convert(item[1])), value.items()))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RuleCreateRequestRule):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RuleCreateRequestRule):
            return True

        return self.to_dict() != other.to_dict()
