"""
DEP Authorization Service

Draft contract for the WP4 Authorization Service. See docs/design/design-005-authorization-service-api.md.  One typed endpoint per operation, so a generated client exposes one function per decision. Operations without an endpoint of their own go through /v1/decisions/privileged-operations.  A decision is returned with HTTP 200 whether it permits or denies. Any non-200 response is an error, and PEPs MUST treat it as a deny.  Subject claims (entitlements, acr) come from the caller's own OAuth2 bearer token, validated by this service, not from the request body. The body carries only what the token cannot supply: which subject the decision concerns (for logging, and for credentials that carry no token at all, such as the root bootstrap) and resource ownership facts the PEP resolves from its own database.   # noqa: E501

The version of the OpenAPI document: 0.1.0-draft
Generated by: https://openapi-generator.tech
"""

try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401

import six

from rucio_authz_client.configuration import Configuration


class Rule:
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"id": "object", "owner": "object", "target": "Did"}

    attribute_map = {"id": "id", "owner": "owner", "target": "target"}

    def __init__(self, id=None, owner=None, target=None, local_vars_configuration=None):  # noqa: E501
        """Rule - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._owner = None
        self._target = None
        self.discriminator = None

        self.id = id
        self.owner = owner
        self.target = target

    @property
    def id(self):
        """Gets the id of this Rule.  # noqa: E501


        :return: The id of this Rule.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Rule.


        :param id: The id of this Rule.  # noqa: E501
        :type id: object
        """

        self._id = id

    @property
    def owner(self):
        """Gets the owner of this Rule.  # noqa: E501

        Account that owns the rule.  # noqa: E501

        :return: The owner of this Rule.  # noqa: E501
        :rtype: object
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this Rule.

        Account that owns the rule.  # noqa: E501

        :param owner: The owner of this Rule.  # noqa: E501
        :type owner: object
        """

        self._owner = owner

    @property
    def target(self):
        """Gets the target of this Rule.  # noqa: E501


        :return: The target of this Rule.  # noqa: E501
        :rtype: Did
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this Rule.


        :param target: The target of this Rule.  # noqa: E501
        :type target: Did
        """
        if self.local_vars_configuration.client_side_validation and target is None:  # noqa: E501
            raise ValueError("Invalid value for `target`, must not be `None`")  # noqa: E501

        self._target = target

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(lambda x: convert(x), value))
            elif isinstance(value, dict):
                result[attr] = dict(map(lambda item: (item[0], convert(item[1])), value.items()))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Rule):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Rule):
            return True

        return self.to_dict() != other.to_dict()
