# coding: utf-8

"""
    DEP Authorization Service

    Draft contract for the WP4 Authorization Service. See docs/design/design-005-authorization-service-api.md.  One typed endpoint per operation, so a generated client exposes one function per decision. Operations without an endpoint of their own go through /v1/decisions/privileged-operations.  A decision is returned with HTTP 200 whether it permits or denies. Any non-200 response is an error, and PEPs MUST treat it as a deny.  Subject claims (entitlements, acr) come from the caller's own OAuth2 bearer token, validated by this service, not from the request body. The body carries only what the token cannot supply: which subject the decision concerns (for logging, and for credentials that carry no token at all, such as the root bootstrap) and resource ownership facts the PEP resolves from its own database.   # noqa: E501

    The version of the OpenAPI document: 0.1.0-draft
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from rucio_authz_client.configuration import Configuration


class RseUpdateRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'subject': 'Subject',
        'rse': 'Rse',
        'changes': 'RseUpdateRequestChanges',
        'context': 'Context'
    }

    attribute_map = {
        'subject': 'subject',
        'rse': 'rse',
        'changes': 'changes',
        'context': 'context'
    }

    def __init__(self, subject=None, rse=None, changes=None, context=None, local_vars_configuration=None):  # noqa: E501
        """RseUpdateRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._subject = None
        self._rse = None
        self._changes = None
        self._context = None
        self.discriminator = None

        self.subject = subject
        self.rse = rse
        self.changes = changes
        self.context = context

    @property
    def subject(self):
        """Gets the subject of this RseUpdateRequest.  # noqa: E501


        :return: The subject of this RseUpdateRequest.  # noqa: E501
        :rtype: Subject
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this RseUpdateRequest.


        :param subject: The subject of this RseUpdateRequest.  # noqa: E501
        :type subject: Subject
        """
        if self.local_vars_configuration.client_side_validation and subject is None:  # noqa: E501
            raise ValueError("Invalid value for `subject`, must not be `None`")  # noqa: E501

        self._subject = subject

    @property
    def rse(self):
        """Gets the rse of this RseUpdateRequest.  # noqa: E501


        :return: The rse of this RseUpdateRequest.  # noqa: E501
        :rtype: Rse
        """
        return self._rse

    @rse.setter
    def rse(self, rse):
        """Sets the rse of this RseUpdateRequest.


        :param rse: The rse of this RseUpdateRequest.  # noqa: E501
        :type rse: Rse
        """
        if self.local_vars_configuration.client_side_validation and rse is None:  # noqa: E501
            raise ValueError("Invalid value for `rse`, must not be `None`")  # noqa: E501

        self._rse = rse

    @property
    def changes(self):
        """Gets the changes of this RseUpdateRequest.  # noqa: E501


        :return: The changes of this RseUpdateRequest.  # noqa: E501
        :rtype: RseUpdateRequestChanges
        """
        return self._changes

    @changes.setter
    def changes(self, changes):
        """Sets the changes of this RseUpdateRequest.


        :param changes: The changes of this RseUpdateRequest.  # noqa: E501
        :type changes: RseUpdateRequestChanges
        """
        if self.local_vars_configuration.client_side_validation and changes is None:  # noqa: E501
            raise ValueError("Invalid value for `changes`, must not be `None`")  # noqa: E501

        self._changes = changes

    @property
    def context(self):
        """Gets the context of this RseUpdateRequest.  # noqa: E501


        :return: The context of this RseUpdateRequest.  # noqa: E501
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this RseUpdateRequest.


        :param context: The context of this RseUpdateRequest.  # noqa: E501
        :type context: Context
        """
        if self.local_vars_configuration.client_side_validation and context is None:  # noqa: E501
            raise ValueError("Invalid value for `context`, must not be `None`")  # noqa: E501

        self._context = context

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RseUpdateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RseUpdateRequest):
            return True

        return self.to_dict() != other.to_dict()
