# Licensed under the Apache License, Version 2.0
"""
Phase 7 permission module — dispatches to authz-service via its generated
client (rucio_authz_client, generated by openapi-generator's python-legacy
generator — see the parent repo's Makefile `generate-client-phase7` target
and services/authorization-service/docs/python39-constraint.md for why
this generator, not openapi-python-client, is used here: it's the only
one tried whose output imports cleanly on Python 3.9, which rucio-server
is pinned to).

Synchronous by construction — python-legacy's client has no asyncio
variant, so no event-loop wrapping is needed here at all.

Scope: OIDC-authenticated accounts only. get_token_for_account_operation
requires an existing OIDC subject token on file; x509/userpass/SSH/GSS
accounts have none and get an explicit deny below, not a silent fallback.
That's a deliberate scope decision, not an oversight.
"""

import logging
import os
from typing import TYPE_CHECKING, Any

from rucio_authz_client.api.dids_api import DidsApi
from rucio_authz_client.api.privileged_api import PrivilegedApi
from rucio_authz_client.api.protocols_api import ProtocolsApi
from rucio_authz_client.api.replicas_api import ReplicasApi
from rucio_authz_client.api.rses_api import RsesApi
from rucio_authz_client.api.rules_api import RulesApi
from rucio_authz_client.api_client import ApiClient
from rucio_authz_client.configuration import Configuration
from rucio_authz_client.exceptions import ApiException
from rucio_authz_client.models.context import Context
from rucio_authz_client.models.did import Did
from rucio_authz_client.models.did_attach_request import DidAttachRequest
from rucio_authz_client.models.did_create_request import DidCreateRequest
from rucio_authz_client.models.did_detach_request import DidDetachRequest
from rucio_authz_client.models.privileged_operation_request import PrivilegedOperationRequest
from rucio_authz_client.models.protocol import Protocol
from rucio_authz_client.models.protocol_create_request import ProtocolCreateRequest
from rucio_authz_client.models.protocol_delete_request import ProtocolDeleteRequest
from rucio_authz_client.models.protocol_update_request import ProtocolUpdateRequest
from rucio_authz_client.models.replica_delete_request import ReplicaDeleteRequest
from rucio_authz_client.models.replica_register_request import ReplicaRegisterRequest
from rucio_authz_client.models.rse import Rse
from rucio_authz_client.models.rse_attribute_delete_request import RseAttributeDeleteRequest
from rucio_authz_client.models.rse_attribute_delete_request_attribute import (
    RseAttributeDeleteRequestAttribute,
)
from rucio_authz_client.models.rse_attribute_set_request import RseAttributeSetRequest
from rucio_authz_client.models.rse_attribute_set_request_attribute import (
    RseAttributeSetRequestAttribute,
)
from rucio_authz_client.models.rse_create_request import RseCreateRequest
from rucio_authz_client.models.rse_delete_request import RseDeleteRequest
from rucio_authz_client.models.rse_update_request import RseUpdateRequest
from rucio_authz_client.models.rse_update_request_changes import RseUpdateRequestChanges
from rucio_authz_client.models.rule import Rule
from rucio_authz_client.models.rule_create_request import RuleCreateRequest
from rucio_authz_client.models.rule_create_request_rule import RuleCreateRequestRule
from rucio_authz_client.models.rule_delete_request import RuleDeleteRequest
from rucio_authz_client.models.rule_update_request import RuleUpdateRequest
from rucio_authz_client.models.rule_update_request_changes import RuleUpdateRequestChanges
from rucio_authz_client.models.scope import Scope
from rucio_authz_client.models.subject import Subject

if TYPE_CHECKING:
    from typing import Optional

    from rucio.common.types import InternalAccount
    from rucio.core.permission import PermissionResult
    from sqlalchemy.orm import Session

log = logging.getLogger(__name__)

_DEBUG_INPUT = os.environ.get("RUCIO_OPA_DEBUG_INPUT", "").strip() in ("1", "true", "True")

AUTHZ_SERVICE_URL = os.environ.get("AUTHZ_SERVICE_URL", "http://localhost:8000")
AUTHZ_AUDIENCE = os.environ.get("AUTHZ_OIDC_AUDIENCE", "authz-service")
AUTHZ_SCOPE = os.environ.get("AUTHZ_REQUIRED_SCOPE", "pep:rucio")
_VO = os.environ.get("AUTHZ_VO", "def")

_RULE_ID_ACTIONS: frozenset[str] = frozenset({"del_rule", "update_rule"})


def _client(token: str) -> ApiClient:
    config = Configuration()
    config.host = AUTHZ_SERVICE_URL
    config.access_token = token
    return ApiClient(config)


def has_permission(
    issuer: "InternalAccount",
    action: str,
    kwargs: dict[str, Any],
    *,
    session: "Optional[Session]" = None,
) -> "PermissionResult":
    from rucio.core.permission import PermissionResult

    try:
        token = _authz_token(issuer, session)
    except Exception:
        log.exception("authz-service: could not obtain a scoped token for issuer=%s", issuer)
        return PermissionResult(False, "Authorization engine unreachable (no token)")

    if token is None:
        log.warning("authz-service: no scoped token available for issuer=%s", issuer)
        return PermissionResult(False, "No authz-service token available for this identity")

    try:
        call, body = _build_request(issuer, action, kwargs, session)
    except Exception:
        log.exception("authz-service: request body construction failed for action=%s", action)
        return PermissionResult(False, "Internal authorization failure: payload construction error")

    if _DEBUG_INPUT:
        log.warning("authz-service request for action=%s: %s", action, body)

    try:
        client = _client(token)
        decision = call(client, body)
    except ApiException as exc:
        # 400/401/403/500 are all Problem responses per the contract — the
        # PEP treats every one of them as a deny, not just 403.
        log.warning("authz-service %s -> HTTP %s: %s", action, exc.status, exc.body)
        return PermissionResult(False, f"authz-service returned {exc.status} for action={action}")
    except Exception as exc:
        log.critical("authz-service call failed for action=%s: %s", action, exc, exc_info=True)
        return PermissionResult(False, "Authorization engine unreachable (system degraded)")

    allowed = bool(decision.decision)
    return PermissionResult(allowed, "" if allowed else "Access denied by authz-service")


def _authz_token(issuer: "InternalAccount", session: "Optional[Session]") -> "Optional[str]":
    from rucio.core.oidc import get_token_for_account_operation

    token_dict = get_token_for_account_operation(
        issuer,
        req_audience=AUTHZ_AUDIENCE,
        req_scope=AUTHZ_SCOPE,
        admin=False,
        session=session,
    )
    return token_dict["token"] if token_dict else None


def _subject(issuer: "InternalAccount") -> Subject:
    # UNVERIFIED: confirm Subject.type takes a plain string ("rucio_account" /
    # "oidc_subject") per the command above, not an enum wrapper class.
    kind = "rucio_account" if issuer.external == "root" else "oidc_subject"
    return Subject(type=kind, id=issuer.external)


def _context() -> Context:
    return Context(vo=_VO)


def _scope_owner(scope: Any, session: "Optional[Session]") -> str:
    """The scope's real owning account — NOT the requesting issuer."""
    if session is None:
        log.warning("authz-service: no session available to resolve scope owner for %s", scope)
        return str(scope)
    try:
        from rucio.common.types import InternalScope
        from rucio.core.scope import list_scopes_with_account

        internal_scope = scope if hasattr(scope, "internal") else InternalScope(scope, vo=_VO)
        rows = list(list_scopes_with_account(filter_={"scope": internal_scope}, session=session))
        if not rows:
            log.warning("authz-service: scope %s has no owning account", internal_scope)
            return internal_scope.external
        return rows[0]["account"].external
    except Exception:
        log.exception("authz-service: scope owner lookup failed for %s", scope)
        return str(scope)


def _did(scope: Any, name: str, session: "Optional[Session]") -> Did:
    owner = _scope_owner(scope, session)
    scope_name = scope.external if hasattr(scope, "external") else str(scope)
    return Did(scope=Scope(name=scope_name, owner=owner), name=name)


def _rule_facts(
    action: str, kwargs: dict[str, Any], session: "Optional[Session]"
) -> dict[str, str]:
    if action not in _RULE_ID_ACTIONS or session is None:
        return {}
    rule_id = kwargs.get("rule_id")
    if not rule_id:
        return {}
    try:
        from rucio.common.exception import RuleNotFound
        from rucio.core.rule import get_rule
    except ImportError:
        return {}
    try:
        row = get_rule(rule_id, session=session)
    except RuleNotFound:
        return {}
    except Exception:
        log.exception("authz-service: could not resolve rule %s", rule_id)
        return {}
    return {"rule_owner": row["account"].external, "rule_scope": row["scope"].external}


def _externalise(value: Any) -> Any:
    from enum import Enum

    if hasattr(value, "external"):
        return value.external
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, dict):
        return {k: _externalise(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_externalise(v) for v in value]
    return value


# Per-action builders: (call(client, body) -> Decision, request body)


def _b_rule_create(issuer, kwargs, facts, session):
    body = RuleCreateRequest(
        subject=_subject(issuer),
        rule=RuleCreateRequestRule(
            owner=str(kwargs["account"]),
            locked=kwargs["locked"],
            rse_expression=kwargs.get("rse_expression"),
            source_rse_expression=kwargs.get("source_rse_expression"),
            dids=[_did(d["scope"], d["name"], session) for d in kwargs.get("dids", [])],
        ),
        context=_context(),
    )
    return (lambda c, b: RulesApi(c).authorize_rule_create(b)), body


def _b_rule_update(issuer, kwargs, facts, session):
    body = RuleUpdateRequest(
        subject=_subject(issuer),
        rule=Rule(
            id=kwargs["rule_id"],
            owner=facts.get("rule_owner", ""),
            target=_did(facts.get("rule_scope", ""), "", session),
        ),
        changes=RuleUpdateRequestChanges(
            **{
                k: v
                for k, v in (kwargs.get("options") or {}).items()
                if k in ("owner", "lifetime", "rse_expression")
            }
        ),
        context=_context(),
    )
    return (lambda c, b: RulesApi(c).authorize_rule_update(b)), body


def _b_rule_delete(issuer, kwargs, facts, session):
    body = RuleDeleteRequest(
        subject=_subject(issuer),
        rule=Rule(
            id=kwargs["rule_id"],
            owner=facts.get("rule_owner", ""),
            target=_did(facts.get("rule_scope", ""), "", session),
        ),
        context=_context(),
    )
    return (lambda c, b: RulesApi(c).authorize_rule_delete(b)), body


def _b_dids_create(issuer, kwargs, facts, session):
    dids = kwargs.get("dids") or [{"scope": kwargs.get("scope"), "name": kwargs.get("name")}]
    body = DidCreateRequest(
        subject=_subject(issuer),
        dids=[_did(d["scope"], d["name"], session) for d in dids],
        context=_context(),
    )
    return (lambda c, b: DidsApi(c).authorize_did_create(b)), body


def _b_dids_attach(issuer, kwargs, facts, session):
    attachments = kwargs.get("attachments") or [
        {"scope": kwargs.get("scope"), "name": kwargs.get("name"), "dids": []}
    ]
    # UNVERIFIED: DidAttachRequest.attachments item shape — confirm via the
    # command above whether it expects dicts or a nested model class.
    body = DidAttachRequest(
        subject=_subject(issuer),
        attachments=[
            {
                "parent": _did(a["scope"], a["name"], session),
                "children": [_did(c["scope"], c["name"], session) for c in a.get("dids", [])],
            }
            for a in attachments
        ],
        context=_context(),
    )
    return (lambda c, b: DidsApi(c).authorize_did_attach(b)), body


def _b_dids_detach(issuer, kwargs, facts, session):
    body = DidDetachRequest(
        subject=_subject(issuer),
        parent=_did(kwargs["scope"], kwargs["name"], session),
        children=[],
        context=_context(),
    )
    return (lambda c, b: DidsApi(c).authorize_did_detach(b)), body


def _b_rse_create(issuer, kwargs, facts, session):
    body = RseCreateRequest(
        subject=_subject(issuer), rse=Rse(name=kwargs["rse"]), context=_context()
    )
    return (lambda c, b: RsesApi(c).authorize_rse_create(b)), body


def _b_rse_update(issuer, kwargs, facts, session):
    params = kwargs.get("parameters", {}) or {}
    changes = (
        RseUpdateRequestChanges(name=params["rse"])
        if "rse" in params
        else RseUpdateRequestChanges()
    )
    body = RseUpdateRequest(
        subject=_subject(issuer),
        rse=Rse(name=kwargs["rse"]),
        changes=changes,
        context=_context(),
    )
    return (lambda c, b: RsesApi(c).authorize_rse_update(b)), body


def _b_rse_delete(issuer, kwargs, facts, session):
    body = RseDeleteRequest(
        subject=_subject(issuer), rse=Rse(name=kwargs["rse"]), context=_context()
    )
    return (lambda c, b: RsesApi(c).authorize_rse_delete(b)), body


def _b_rse_attr_set(issuer, kwargs, facts, session):
    body = RseAttributeSetRequest(
        subject=_subject(issuer),
        rse=Rse(name=kwargs["rse"]),
        attribute=RseAttributeSetRequestAttribute(key=kwargs["key"]),
        context=_context(),
    )
    return (lambda c, b: RsesApi(c).authorize_rse_attribute_set(b)), body


def _b_rse_attr_delete(issuer, kwargs, facts, session):
    body = RseAttributeDeleteRequest(
        subject=_subject(issuer),
        rse=Rse(name=kwargs["rse"]),
        attribute=RseAttributeDeleteRequestAttribute(key=kwargs["key"]),
        context=_context(),
    )
    return (lambda c, b: RsesApi(c).authorize_rse_attribute_delete(b)), body


def _b_protocol_create(issuer, kwargs, facts, session):
    body = ProtocolCreateRequest(
        subject=_subject(issuer),
        rse=Rse(name=kwargs["rse"]),
        protocol=Protocol(scheme=kwargs.get("scheme")),
        context=_context(),
    )
    return (lambda c, b: ProtocolsApi(c).authorize_protocol_create(b)), body


def _b_protocol_update(issuer, kwargs, facts, session):
    body = ProtocolUpdateRequest(
        subject=_subject(issuer),
        rse=Rse(name=kwargs["rse"]),
        protocol=Protocol(scheme=kwargs.get("scheme")),
        context=_context(),
    )
    return (lambda c, b: ProtocolsApi(c).authorize_protocol_update(b)), body


def _b_protocol_delete(issuer, kwargs, facts, session):
    body = ProtocolDeleteRequest(
        subject=_subject(issuer),
        rse=Rse(name=kwargs["rse"]),
        protocol=Protocol(scheme=kwargs.get("scheme")),
        context=_context(),
    )
    return (lambda c, b: ProtocolsApi(c).authorize_protocol_delete(b)), body


def _b_replicas_register(issuer, kwargs, facts, session):
    files = kwargs.get("files") or []
    body = ReplicaRegisterRequest(
        subject=_subject(issuer),
        rse=Rse(name=kwargs.get("rse")),
        files=[_did(f["scope"], f["name"], session) for f in files],
        context=_context(),
    )
    return (lambda c, b: ReplicasApi(c).authorize_replica_register(b)), body


def _b_replicas_delete(issuer, kwargs, facts, session):
    files = kwargs.get("files") or []
    body = ReplicaDeleteRequest(
        subject=_subject(issuer),
        rse=Rse(name=kwargs.get("rse")),
        files=[_did(f["scope"], f["name"], session) for f in files],
        context=_context(),
    )
    return (lambda c, b: ReplicasApi(c).authorize_replica_delete(b)), body


def _b_privileged(issuer, kwargs, facts, session, *, action):
    body = PrivilegedOperationRequest(
        subject=_subject(issuer), operation=action, context=_context()
    )
    return (lambda c, b: PrivilegedApi(c).authorize_privileged_operation(b)), body


_DISPATCH = {
    "add_rule": _b_rule_create,
    "update_rule": _b_rule_update,
    "del_rule": _b_rule_delete,
    "add_did": _b_dids_create,
    "add_dids": _b_dids_create,
    "attach_dids": _b_dids_attach,
    "attach_dids_to_dids": _b_dids_attach,
    "detach_dids": _b_dids_detach,
    "add_rse": _b_rse_create,
    "update_rse": _b_rse_update,
    "del_rse": _b_rse_delete,
    "add_rse_attribute": _b_rse_attr_set,
    "del_rse_attribute": _b_rse_attr_delete,
    "add_protocol": _b_protocol_create,
    "update_protocol": _b_protocol_update,
    "del_protocol": _b_protocol_delete,
    "add_replicas": _b_replicas_register,
    "delete_replicas": _b_replicas_delete,
}


def _build_request(issuer, action, kwargs, session):
    facts = _rule_facts(action, kwargs, session)
    builder = _DISPATCH.get(action)
    if builder is None:
        return _b_privileged(issuer, kwargs, facts, session, action=action)
    return builder(issuer, kwargs, facts, session)
