"""
DEP Authorization Service

Draft contract for the WP4 Authorization Service. See docs/design/design-005-authorization-service-api.md.  One typed endpoint per operation, so a generated client exposes one function per decision. Operations without an endpoint of their own go through /v1/decisions/privileged-operations.  A decision is returned with HTTP 200 whether it permits or denies. Any non-200 response is an error, and PEPs MUST treat it as a deny.  Subject claims (entitlements, acr) come from the caller's own OAuth2 bearer token, validated by this service, not from the request body. The body carries only what the token cannot supply: which subject the decision concerns (for logging, and for credentials that carry no token at all, such as the root bootstrap) and resource ownership facts the PEP resolves from its own database.   # noqa: E501

The version of the OpenAPI document: 0.1.0-draft
Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from rucio_authz_client.api_client import ApiClient
from rucio_authz_client.exceptions import ApiTypeError, ApiValueError  # noqa: F401


class PrivilegedApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def authorize_privileged_operation(self, privileged_operation_request, **kwargs):  # noqa: E501
        """May the subject perform an operation reserved for privileged subjects?  # noqa: E501

        For every consumer operation without an endpoint of its own (e.g. update_replicas_states, add_account, add_scope, approve_rule). The policy for all of them is: privileged subjects only. An operation that has its own endpoint is rejected with 400, so each operation has exactly one route.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.authorize_privileged_operation(privileged_operation_request, async_req=True)
        >>> result = thread.get()

        :param privileged_operation_request: (required)
        :type privileged_operation_request: PrivilegedOperationRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: Decision
        """
        kwargs["_return_http_data_only"] = True
        return self.authorize_privileged_operation_with_http_info(
            privileged_operation_request, **kwargs
        )  # noqa: E501

    def authorize_privileged_operation_with_http_info(self, privileged_operation_request, **kwargs):  # noqa: E501
        """May the subject perform an operation reserved for privileged subjects?  # noqa: E501

        For every consumer operation without an endpoint of its own (e.g. update_replicas_states, add_account, add_scope, approve_rule). The policy for all of them is: privileged subjects only. An operation that has its own endpoint is rejected with 400, so each operation has exactly one route.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.authorize_privileged_operation_with_http_info(privileged_operation_request, async_req=True)
        >>> result = thread.get()

        :param privileged_operation_request: (required)
        :type privileged_operation_request: PrivilegedOperationRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(Decision, status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = ["privileged_operation_request"]
        all_params.extend(
            [
                "async_req",
                "_return_http_data_only",
                "_preload_content",
                "_request_timeout",
                "_request_auth",
                "_content_type",
                "_headers",
            ]
        )

        for key, val in six.iteritems(local_var_params["kwargs"]):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method authorize_privileged_operation" % key
                )
            local_var_params[key] = val
        del local_var_params["kwargs"]
        # verify the required parameter 'privileged_operation_request' is set
        if (
            self.api_client.client_side_validation
            and local_var_params.get("privileged_operation_request") is None
        ):  # noqa: E501
            raise ApiValueError(
                "Missing the required parameter `privileged_operation_request` when calling `authorize_privileged_operation`"
            )  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = dict(local_var_params.get("_headers", {}))

        form_params = []
        local_var_files = {}

        body_params = None
        if "privileged_operation_request" in local_var_params:
            body_params = local_var_params["privileged_operation_request"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json", "application/problem+json"]
        )  # noqa: E501

        # HTTP header `Content-Type`
        content_types_list = local_var_params.get(
            "_content_type",
            self.api_client.select_header_content_type(["application/json"], "POST", body_params),
        )  # noqa: E501
        if content_types_list:
            header_params["Content-Type"] = content_types_list

        # Authentication setting
        auth_settings = ["oauth2"]  # noqa: E501

        response_types_map = {
            200: "Decision",
            400: "Problem",
            401: "Problem",
            403: "Problem",
            500: "Problem",
        }

        return self.api_client.call_api(
            "/v1/decisions/privileged-operations",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_types_map=response_types_map,
            auth_settings=auth_settings,
            async_req=local_var_params.get("async_req"),
            _return_http_data_only=local_var_params.get("_return_http_data_only"),  # noqa: E501
            _preload_content=local_var_params.get("_preload_content", True),
            _request_timeout=local_var_params.get("_request_timeout"),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get("_request_auth"),
        )
